### ISSUE TITLE
Changing CPU governors restarts device

### ISSUE THREAD

**Issue by t0rzz** [CruelKernel/samsung-exynos9820#172]
Hello,
I compiled cruel enabling powersave, conservative, performance CPU Governors.
I checked the  /sys/ properties to see if they were actually enabled, and they are.
Whenever I try to change the governor to anything different from "powersave" or "performance", my G975F Immediately restarts and goes back to schedutil.
Are the other governors _actually_ implemented?

Thank you.

Francesco Menghetti

**Comment by evdenis** [comment]
Hi,

Yep, this is a known problem.
Samsung didn't care about these in-kernel schedulers and broke them.
Honestly, there is no point in using them. Schedutil is the best.
Since I don't have the device anymore I will not try to fix these crashes, but I can remove the configuration settings.
IO schedulers should work well, except for bfq. As long as I remember there are some problems with bfq.

**Comment by t0rzz** [comment]
Ok man, thank you very much! I'll stick with schedutil.
