### ISSUE TITLE
Magisk v25

### ISSUE THREAD

**Issue by t0rzz** [CruelKernel/samsung-exynos9820#198]
Hi,
Is there any particular reason for not supporting new Magisk version? I'm not into kernel building for Android, but I'd like to know how much changed for a kernel to support it.

Thank you

**Comment by t0rzz** [comment]
@evdenis ?

**Comment by evdenis** [comment]
Magisk > 24.3 will not be supported.

**Comment by t0rzz** [comment]
> Magisk > 24.3 will not be supported.

Yes that was your initial statement. Can I ask you the REASON?

**Comment by evdenis** [comment]
I don't have a phone for this kernel for more than a year already. Since when this project is archived and no active development is done. I only add new samsung sources because it usually doesn't require from me much time and it's save to do without a phone to test/debug. I checked the Magisk v25 changes and I didn't find an easy and obvious way to add a support for it to the kernel. It means I need a phone close to me and highly likely I need to spend week evenings trying to find the best and convenient way to support v25. I don't have a phone and I don't have that much free time to spend on kernel which I will not use anyways.

**Comment by t0rzz** [comment]
> I don't have a phone for this kernel for more than a year already. Since when this project is archived and no active development is done. I only add new samsung sources because it usually doesn't require from me much time and it's save to do without a phone to test/debug. I checked the Magisk v25 changes and I didn't find an easy and obvious way to add a support for it to the kernel. It means I need a phone close to me and highly likely I need to spend week evenings trying to find the best and convenient way to support v25. I don't have a phone and I don't have that much free time to spend on kernel which I will not use anyways.

I understand. Thanks for your time and your efforts. If you ever find a way around the new Magisk changes that’d be much appreciated anyway. Have a good day Denis!

**Comment by evdenis** [comment]
Thanks for understanding!
